### ISSUE TITLE
Classes in tags rendered incorrectly

### ISSUE THREAD

**Issue by mike706574** [lambdaisland/hiccup#7]
I'm using version `0.0.25`, and classes specified in tags aren't being rendered correctly:

```clojure
user> (require '[lambdaisland.hiccup :as hiccup])
nil
user> (hiccup/render [:div.foo] {:doctype? false})
"<div class=\"clojure.lang.LazySeq@18ce5\"></div>"
```

Some test cases that would currently fail if added:

```clojure
(testing "classes in tags"
  (is (= (hiccup/render [:div.foo] {:doctype? false})
         "<div class=\"foo\"></div>"))

  (is (= (hiccup/render [:div.foo.bar] {:doctype? false})
         "<div class=\"foo bar\"></div>"))

  (is (= (hiccup/render [:div.foo {:class "bar"}] {:doctype? false})
         "<div class=\"foo bar\"></div>"))

  (is (= (hiccup/render [:div.foo {:class "foo"}] {:doctype? false})
         "<div class=\"foo foo\"></div>")))
```

In `lambdaisland.hiccup/nodify`, it looks like classes from the tag get included in the value for the keyword attribute `:class`, but the string attribute `"class"` is the one that gets joined to create a valid class value.

**Comment by oxalorg** [comment]
Thanks for creating the issue @mike706574 🙌 

Just confirmed that yes this is happening in `0.0.25` but was not happening in 5db0e3436fc70ad0a09db375f7bdb5c19b21b722 which was before the #5 PR got merged in.

**Comment by oxalorg** [comment]
Merged PR, and released a new version. Fix is now available:

```
com.lambdaisland/hiccup {:mvn/version "0.0.33"}
```

**Comment by mike706574** [comment]
> Merged PR, and released a new version. Fix is now available:
> 
> ```
> com.lambdaisland/hiccup {:mvn/version "0.0.33"}
> ```

Thanks!
